# Barangay System – One-Click Setup (Windows)
# Run from the project root:  powershell -ExecutionPolicy Bypass -File scripts\windows\setup.ps1
# Or double-click  packaging\windows_bundle\SETUP.bat  (auto-elevates to admin)

param(
    [string]$Port = 5000,
    [string]$ServiceName = "BarangaySystem"
)

$ErrorActionPreference = "Stop"

# ── helpers ──────────────────────────────────────────────────────────
function Step { Write-Host ("`n" + "─" * 52) -ForegroundColor Cyan; Write-Host "  $args" -ForegroundColor Cyan; Write-Host ("─" * 52) -ForegroundColor Cyan }
function Ok   { Write-Host "    ok: $args" -ForegroundColor Green }
function Warn { Write-Host "  warn: $args" -ForegroundColor Yellow }
function Fail { Write-Host "  FAIL: $args" -ForegroundColor Red; pause; exit 1 }

# ── resolve project root ─────────────────────────────────────────────
$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$AppDir     = Split-Path -Parent (Split-Path -Parent $ScriptDir)
$BundleDir  = Join-Path $AppDir "packaging\windows_bundle"
$DataDir    = Join-Path $AppDir "data"
$NssmBin    = Join-Path $BundleDir "nssm.exe"

Step "Barangay System Setup"

if (-not (Test-Path $NssmBin)) {
    Fail "nssm.exe not found at $NssmBin – make sure you extracted the whole project folder."
}

Set-Location $AppDir
Ok "Project directory: $AppDir"

# ── admin check ──────────────────────────────────────────────────────
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Warn "Setup needs administrator privileges (NSSM + firewall). Restarting elevated…"
    Start-Process PowerShell -Verb RunAs -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`" -Port $Port -ServiceName $ServiceName"
    exit 0
}
Ok "Running with administrator privileges"

# ── Python ───────────────────────────────────────────────────────────
Step "Checking Python"
$python = Get-Command python -ErrorAction SilentlyContinue
if ($python) {
    Ok "Python found: $($python.Source)"
} else {
    Warn "Python not found – installing via winget (this may take a few minutes)..."
    winget install Python.Python.3.12 --accept-package-agreements --accept-source-agreements
    $env:Path = [Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [Environment]::GetEnvironmentVariable("Path", "User")
    $python = Get-Command python -ErrorAction SilentlyContinue
    if (-not $python) { Fail "Python installation failed – try installing manually from https://python.org" }
    Ok "Python 3.12 installed"
}

# ── uv ───────────────────────────────────────────────────────────────
Step "Checking uv"
$uv = Get-Command uv -ErrorAction SilentlyContinue
if ($uv) {
    Ok "uv found: $($uv.Source)"
} else {
    Warn "uv not found – installing via pip..."
    python -m pip install uv
    $uv = Get-Command uv -ErrorAction SilentlyContinue
    if (-not $uv) { Fail "uv installation failed" }
    Ok "uv installed"
}

# ── .env ─────────────────────────────────────────────────────────────
Step "Configuring .env"
$envFile = Join-Path $AppDir ".env"
if (Test-Path $envFile) {
    Ok ".env already exists – keeping existing configuration"
} else {
    $secret = [System.Guid]::NewGuid().ToString("N")
    $dbFullPath = (Join-Path (Join-Path $AppDir "data") "barangay.db").Replace("\", "/")
    @"
# Auto-generated by setup.ps1 – edit as needed
APP_ENV=production
SECRET_KEY=$secret
DATABASE_URL=sqlite:///$dbFullPath
HOST=0.0.0.0
PORT=$Port
SESSION_COOKIE_SECURE=False
SESSION_IDLE_TIMEOUT_SECONDS=3600
SESSION_ABSOLUTE_TIMEOUT_SECONDS=43200
"@ | Out-File -Encoding utf8 $envFile
    Ok ".env created with random SECRET_KEY"
}

# ── data directories ─────────────────────────────────────────────────
Step "Creating data directories"
$dirs = @(
    $DataDir,
    "$DataDir\uploads",
    "$DataDir\documents",
    "$DataDir\templates",
    "$DataDir\backups",
    "$DataDir\logs",
    "$AppDir\frontend\static\uploads"
)
foreach ($d in $dirs) {
    New-Item -ItemType Directory -Path $d -Force | Out-Null
    Ok "  $d"
}

# ── install dependencies ─────────────────────────────────────────────
Step "Installing project dependencies (uv sync – includes rembg + PyTorch, ~2 min)"
Push-Location $AppDir
try {
    uv sync
    if ($LASTEXITCODE -ne 0) { Fail "uv sync failed" }
    Ok "All dependencies installed"
} finally {
    Pop-Location
}

# ── create database tables + seed data ───────────────────────────────
Step "Initialising database (creating tables + seed data)"
Push-Location $AppDir
try {
    uv run python -c "from barangay_project.app import create_app; app=create_app(); print('Database tables created.')"
    if ($LASTEXITCODE -ne 0) { Fail "Database initialisation failed" }
    Ok "Database ready"
} finally {
    Pop-Location
}

# ── install NSSM service ─────────────────────────────────────────────
Step "Installing Windows service '$ServiceName'"

# Stop and remove any previous installation
& $NssmBin stop    $ServiceName 2>$null
& $NssmBin remove  $ServiceName confirm 2>$null

$uvBin = $uv.Source
& $NssmBin install $ServiceName $uvBin "run waitress-serve --host=0.0.0.0 --port=$Port wsgi:app"
if ($LASTEXITCODE -ne 0) { Fail "NSSM install failed" }

& $NssmBin set $ServiceName AppDirectory $AppDir
& $NssmBin set $ServiceName Start SERVICE_AUTO_START
& $NssmBin set $ServiceName AppStdout "$DataDir\logs\service-out.log"
& $NssmBin set $ServiceName AppStderr "$DataDir\logs\service-err.log"
& $NssmBin set $ServiceName AppRotateFiles 1
& $NssmBin set $ServiceName AppRotateBytes 10485760
Ok "Service registered (auto-start on boot)"

# ── firewall ─────────────────────────────────────────────────────────
Step "Configuring Windows Firewall"
netsh advfirewall firewall delete rule name="$ServiceName" 2>$null
netsh advfirewall firewall add rule name="$ServiceName" dir=in action=allow protocol=tcp localport=$Port
if ($LASTEXITCODE -ne 0) { Warn "Firewall rule may not have been added" }
else { Ok "Firewall rule added for port $Port" }

# ── start service ────────────────────────────────────────────────────
Step "Starting service"
& $NssmBin start $ServiceName
if ($LASTEXITCODE -ne 0) {
    Warn "Service start returned error code $LASTEXITCODE"
    Warn "Check: $DataDir\logs\service-err.log"
} else {
    Ok "Service is running"
}

# ── desktop shortcut ─────────────────────────────────────────────────
Step "Creating desktop shortcut"
try {
    $WshShell = New-Object -ComObject WScript.Shell
    $Shortcut = $WshShell.CreateShortcut([System.IO.Path]::Combine([Environment]::GetFolderPath("Desktop"), "Barangay System.url"))
    $Shortcut.TargetPath = "http://localhost:$Port"
    $Shortcut.Save()
    Ok "Shortcut: Barangay System.url"
} catch {
    Warn "Could not create desktop shortcut: $_"
}

# ── open browser ─────────────────────────────────────────────────────
Step "Done"
Write-Host "======================================================================" -ForegroundColor Green
Write-Host "  Barangay System is running on  http://localhost:$Port" -ForegroundColor Green
Write-Host "======================================================================" -ForegroundColor Green
Write-Host "  Default login: admin / admin" -ForegroundColor Yellow
Write-Host "  Change password immediately after first login." -ForegroundColor Yellow

Start-Process "http://localhost:$Port"

pause
