"""
Generate a professional 'Barangay Document — Verified Authentic' image.

Usage:
    python scripts/generate_verification_image.py

Output: frontend/static/uploads/verification/authentic.png

Upload this image to Google Drive, set sharing to "Anyone with the link",
then set PUBLIC_URL in .env to:
    https://drive.google.com/uc?export=view&id=YOUR_FILE_ID
"""
import os
import sys

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("Pillow is required. Install it with: pip install Pillow")
    sys.exit(1)


def find_font(size: int):
    candidates = [
        "C:/Windows/Fonts/segoeui.ttf",
        "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/calibri.ttf",
        "C:/Windows/Fonts/tahoma.ttf",
    ]
    bold_candidates = [
        "C:/Windows/Fonts/segoeuib.ttf",
        "C:/Windows/Fonts/arialbd.ttf",
        "C:/Windows/Fonts/calibrib.ttf",
        "C:/Windows/Fonts/tahomabd.ttf",
    ]
    for path in bold_candidates + candidates:
        if os.path.isfile(path):
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def generate(output_path: str):
    W, H = 800, 600
    img = Image.new("RGB", (W, H), "#ffffff")
    draw = ImageDraw.Draw(img)

    # Header bar
    draw.rectangle([0, 0, W, 90], fill="#a32020")

    # Header text
    font_header = find_font(28)
    draw.text((W // 2, 30), "BARANGAY DOCUMENT", fill="#ffffff", font=font_header, anchor="mt")
    font_sub = find_font(16)
    draw.text((W // 2, 62), "Verification Certificate", fill="#ffcccc", font=font_sub, anchor="mt")

    # Divider line
    draw.rectangle([40, 110, W - 40, 112], fill="#a32020")

    # Shield / check icon (drawn with shapes)
    cx, cy = W // 2, 210
    # Shield outline
    shield_pts = [
        (cx, cy - 60),
        (cx + 50, cy - 40),
        (cx + 50, cy + 10),
        (cx, cy + 60),
        (cx - 50, cy + 10),
        (cx - 50, cy - 40),
    ]
    draw.polygon(shield_pts, fill="#dcfce7", outline="#166534", width=2)
    # Checkmark inside shield
    check_pts = [
        (cx - 20, cy),
        (cx - 5, cy + 18),
        (cx + 25, cy - 18),
    ]
    draw.line(check_pts, fill="#166534", width=5)

    # Main message
    font_main = find_font(24)
    draw.text((W // 2, 310), "This Document is", fill="#333333", font=font_main, anchor="mt")
    font_main_bold = find_font(30)
    draw.text((W // 2, 345), "AUTHENTIC", fill="#166534", font=font_main_bold, anchor="mt")

    # Description
    font_desc = find_font(13)
    draw.text(
        (W // 2, 400),
        "This barangay document has been verified as legitimate.",
        fill="#666666",
        font=font_desc,
        anchor="mt",
    )
    draw.text(
        (W // 2, 422),
        "Scanned via Barangay Document Management System.",
        fill="#666666",
        font=font_desc,
        anchor="mt",
    )

    # Footer bar
    draw.rectangle([0, H - 50, W, H], fill="#f1f1f1")
    font_footer = find_font(11)
    draw.text(
        (W // 2, H - 25),
        "Generated by Barangay Document Management System",
        fill="#999999",
        font=font_footer,
        anchor="mm",
    )

    # Border
    draw.rectangle([0, 0, W - 1, H - 1], outline="#dddddd", width=1)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    img.save(output_path, "PNG")
    print(f"Verification image saved to: {output_path}")
    print(f"Upload this to Google Drive, then set PUBLIC_URL in .env:")
    print(f"  PUBLIC_URL=https://drive.google.com/uc?export=view&id=YOUR_FILE_ID")


if __name__ == "__main__":
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    output = os.path.join(project_root, "frontend", "static", "uploads", "verification", "authentic.png")
    generate(output)
